### ISSUE TITLE
Error 403 on first login

### ISSUE THREAD

**Issue by evnsio** [negz/kuberos#23] opened 2018-02-23 13:26 UTC
I've just setup Kuberos and noticed I get a 403 the first time I login with Google.  The steps to reproduce are as follows:

1. Head to the kuberos address, http://localhost:10003
2. Login with a Google account
3. Redirect happens (to `http://localhost:10003/ui?state...`) 
4. Error message saying "Could not connect to authentication API: 403 Forbidden"

Looking at the network trace, it's the call to `http://localhost:10003/kubecfg?state=0a...` that's presenting the 403.  Screenshots below.

## Error page:
<img width="1195" alt="screen shot 2018-02-23 at 13 21 53" src="https://user-images.githubusercontent.com/6616412/36596160-b551b8ec-189c-11e8-9506-d9e944a009b9.png">

## kubecfg request:
<img width="761" alt="screen shot 2018-02-23 at 13 22 10" src="https://user-images.githubusercontent.com/6616412/36596159-b53d0ec4-189c-11e8-9c01-81f3ef96f0aa.png">

If I carry out steps 1-4 again, everything works as expected.   The behaviour is the same when running on localhost, or when deployed into my cluster with a valid https endpoint.

Happy to help fix if you can point me in the right direction.

**Comment by negz** [comment] 2018-02-26 23:07
Thanks for the high quality bug report!

I expect you're hitting one of the `http.StatusForbidden` cases in https://github.com/negz/kuberos/blob/master/kuberos.go#L233. Does Chrome show anything in the Response tab for the failed request to the `kubecfg` endpoint?

https://github.com/negz/kuberos/blob/master/frontend/src/kuberos.vue#L4 - I think we should probably include `error.response.data` in the error popup you see (any maybe change the "could not connect" wording) to make issues like this a little easier to debug.

**Comment by SEJeff** [comment] 2018-03-01 19:59
This is really easy for me to run into as well, running dex 2.9.0 with 2 replicas in a kubernetes cluster. I just opened up a chrome incognito window and auth'd 4 different times. It happened two times but the first time I didn't have the web inspector open.

Response body:

`invalid state parameter`

Similar headers:

```
Request URL:https://kuberos.[CENSORED]/kubecfg?code=[generated_code]&state=[hashed_state]
Request Method:GET
Status Code:403 Forbidden
Remote Address:7.129.127.5:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Connection:keep-alive
Content-Length:24
Content-Type:text/plain; charset=utf-8
Date:Thu, 01 Mar 2018 19:53:25 GMT
Server:nginx/1.13.8
Strict-Transport-Security:max-age=15724800; includeSubDomains;
X-Content-Type-Options:nosniff

Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:kuberos.[CENSORED]
Referer:https://kuberos.[CENSORED]

Request URL:https://kuberos.[CENSORED]/kubecfg?code=[generated_code]&state=[hashed_state]
Request Method:GET
Status Code:403 Forbidden
Remote Address:7.129.127.5:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Connection:keep-alive
Content-Length:24
Content-Type:text/plain; charset=utf-8
Date:Thu, 01 Mar 2018 19:53:25 GMT
Server:nginx/1.13.8
Strict-Transport-Security:max-age=15724800; includeSubDomains;
X-Content-Type-Options:nosniff

Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:kuberos.[CENSORED]
Referer:https://kuberos.[CENSORED]/ui?code=[generated_code]&state=[hashed_state]
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36
Query String Parameters
view source
view URL encoded
code:[generated_code]
state:[hashed_state]

Request URL:https://kuberos.[CENSORED]/kubecfg?code=[generated_code]&state=[hashed_state]
Request Method:GET
Status Code:403 Forbidden
Remote Address:7.129.127.5:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Connection:keep-alive
Content-Length:24
Content-Type:text/plain; charset=utf-8
Date:Thu, 01 Mar 2018 19:53:25 GMT
Server:nginx/1.13.8
Strict-Transport-Security:max-age=15724800; includeSubDomains;
X-Content-Type-Options:nosniff

Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:kuberos.[CENSORED]
Referer:https://kuberos.[CENSORED]/ui?code=[generated_code]&state=[hashed_state]
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36
Query String Parameters
view source
view URL encoded
code:[generated_code]
state:[hashed_state]/ui?code=[generated_code]&state=[hashed_state]
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36
Query String Parameters
view source
view URL encoded
code:[generated_code]
state:[hashed_state]
```

I'd be happy to build + run a debug copy of kuberos if it helps you track that down.

**Comment by negz** [comment] 2018-03-12 08:13
https://auth0.com/docs/protocols/oauth2/oauth-state

@SEJeff The `invalid state parameter` error you're seeing refers to the OIDC `state` parameter. Per the above link it's a param Kuberos uses to ensure that when Dex redirects your browser back to Kuberos you're still the same person who started the authentication flow.

Specifically in Kuberos's case this works like:
1. You browse to https://kuberos.example.org
1. Kuberos hashes your source IP address and user agent (the `X-Forwarded-For` header overrides your source IP if set) to create a string, then passes that to your browser as the `state`.
1. Kuberos redirects you to Dex to authenticate, including the state.
1. Dex redirects you back to Kuberos, including the state.
1. Kuberos repeats step 2 and compares the states. If they don't match you get an error.

Can you think of any reason this process might be failing for you? I'd expect you to see this error if your source IP or user agent changes between requests.

@evnsio Do you know whether you're seeing the same `invalid state param` error as @SEJeff?

**Comment by negz** [comment] 2018-03-12 08:58
@evnsio @SEJeff `af9266a` won't fix the 403 errors, but should surface them a little better.

**Comment by SEJeff** [comment] 2018-03-20 18:30
With the latest, I'm seeing the 403 errors as `Authentication failed: 403 Forbidden: invalid state parameter: user agent or IP address changed between requests`.

Given the new debug output (very useful, thanks!) I think I have an idea of what the problem is. I've got a kuberos deployment with 3 replicas (for rolling updates to be magical and whatnot for users).

```
2018-03-20T13:22:12.913-0500    INFO    kuberos/kuberos.go:33   request {"host": "k8s-login.carg.k8s", "method": "GET", "url": "/", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36", "addr": "10.129.199.7:33678"}
2018-03-20T13:22:12.913-0500    DEBUG   kuberos/kuberos.go:39   request {"headers": {"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.8"],"Connection":["close"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36"],"X-Forwarded-For":["10.129.0.14"],"X-Forwarded-Host":["k8s-login.carg.k8s"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Uri":["/"],"X-Real-Ip":["10.129.0.14"],"X-Scheme":["https"]}}
2018-03-20T13:22:12.913-0500    DEBUG   kuberos/kuberos.go:228  redirect        {"url": "https://k8s-login.carg.k8s/dex/auth?client_id=kuberos&prompt=consent&redirect_uri=https%3A%2F%2Fk8s-login.carg.k8s%2Fui&response_type=code&scope=openid+profile+email+offline_access+groups&state=3cd8cd277db528ec10456de96ccc91e69dc66992f5f6d6d92f84d0787c74dd95"}
2018-03-20T13:22:26.530-0500    INFO    kuberos/kuberos.go:33   request {"host": "k8s-login.carg.k8s", "method": "GET", "url": "/ui?code=fnqxtfigph2l26f6km335meq7&state=3cd8cd277db528ec10456de96ccc91e69dc66992f5f6d6d92f84d0787c74dd95", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36", "addr": "10.129.209.4:58096"}
2018-03-20T13:22:26.530-0500    DEBUG   kuberos/kuberos.go:39   request {"headers": {"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.8"],"Cache-Control":["max-age=0"],"Connection":["close"],"Referer":["https://k8s-login.carg.k8s/dex/auth/active-directory?req=ze7meqlh62en5qpdbada5lxq3"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36"],"X-Forwarded-For":["10.129.0.17"],"X-Forwarded-Host":["k8s-login.carg.k8s"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Uri":["/ui?code=fnqxtfigph2l26f6km335meq7\u0026state=3cd8cd277db528ec10456de96ccc91e69dc66992f5f6d6d92f84d0787c74dd95"],"X-Real-Ip":["10.129.0.17"],"X-Scheme":["https"]}}
2018-03-20T13:22:29.443-0500    INFO    kuberos/kuberos.go:33   request {"host": "k8s-login.carg.k8s", "method": "GET", "url": "/favicon.ico", "agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36", "addr": "10.129.209.4:58146"}
2018-03-20T13:22:29.443-0500    DEBUG   kuberos/kuberos.go:39   request {"headers": {"Accept":["image/webp,image/apng,image/*,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.8"],"Connection":["close"],"Referer":["https://k8s-login.carg.k8s/ui?code=fnqxtfigph2l26f6km335meq7\u0026state=3cd8cd277db528ec10456de96ccc91e69dc66992f5f6d6d92f84d0787c74dd95"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3067.0 Safari/537.36"],"X-Forwarded-For":["10.129.0.17"],"X-Forwarded-Host":["k8s-login.carg.k8s"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Original-Uri":["/favicon.ico"],"X-Real-Ip":["10.129.0.17"],"X-Scheme":["https"]}}
```

So I did notice that from looking at things, `X-Real-Ip` and `X-Forwarded-For` are the ips of kubelets, not of the clients. Perhaps the ingress isn't properly passing these through? Could that, along with some round robin-ing of the requests by the service load balancer (we use kube-router + ipvs instead of kube-proxy + iptables for scalability and performance reasons) be causing the ip to change and kuberos to reject things?

**Comment by negz** [comment] 2018-03-21 03:54
@SEJeff That could certainly be it. 

We use a pluggable function to generate the state token, so we could certainly make it configurable to help with the issue you're seeing. We'd need some other signals in addition to the user agent though.

**Comment by SEJeff** [comment] 2018-03-23 03:09
What other signals could be used?

**Comment by negz** [comment] 2018-03-23 04:26
@SEJeff Good question; nothing immediately comes to mind. Kuberos doesn't persist anything between requests, so we're effectively limited to things we can determine about each HTTP request we get; i.e. headers, requesting IP, etc.

We could enable a mode that just uses the user agent? On one hand it's not a lot of assurance that the callback to Kuberos from Dex is coming from the same browser that initiated the login, but on the other hand it's not really any worse than your current situation given that Kuberos is seeing Kubelet IPs rather than the real caller's IP.

We could use a [JWT](https://jwt.io) to sign the state token with a shared secret in order to avoid attackers forging state tokens wholesale, but it would still be pretty straightforward to spoof a user agent, get a real signed JWT state token, and use that to masquerade as another user with said user agent.

**Comment by negz** [comment] 2018-06-25 19:48
@SEJeff @evnsio I believe @Miouge1 may have fixed this in https://github.com/negz/kuberos/pull/41.

**Comment by negz** [comment] 2018-06-28 01:45
I'm going to opportunistically mark this closed. Please comment if you run into this issue on the latest build of Kuberos.

**Closed as completed by negz** 2018-06-28 01:45 UTC

**Comment by teerakarna** [comment] 2018-09-20 21:46
Just experienced this issue today. Here's my `values.yaml` that I used to install the Helm chart:

```
kuberos:
  oidcClientURL: https://accounts.google.com
  oidcClientID: REDACTED.apps.googleusercontent.com
  clusters:
  - name: euwest1.test.com
    apiServer: https://api.euwest1.test.com
    caCrt: |
      -----BEGIN CERTIFICATE-----
      REDACTED
      -----END CERTIFICATE-----

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
  hosts:
    - kuberos.test.com
  tls:
    - secretName: kuberos-certificate
      hosts:
        - kuberos.test.com
```

I am using this with cert-manager, external-dns and ingress-nginx, and kube2iam is used by the first two as well.

The error I get when I hit the /ui site is:

```
Authentication failed: 403 : invalid state parameter: user agent or IP address changed between requests
```

But when I go to the base URL, I get redirected to the Google OAuth2 page and see this error:

```
400. That’s an error.

Error: redirect_uri_mismatch
```

Any ideas?
